# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy static HTML to Azure Web App - inbody-cs-conference-agenda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCF1DAA660D74A97918F9E21ED5B839E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04EAB2DB49C44B1AA2BC741202202244 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6461BBD8059F48C9AE724B56C325002D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inbody-cs-conference-agenda'
          slot-name: 'Production'
          package: .
