name: Deploy static files to Azure Web App - inbody-cs-conference-agenda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE38CA40DFB3401AAA1DA56E00213DDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F15031C90AF4D9F8ECF35DFC80C89E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7164D112722F4DB6AF5CA942EDAB4DBB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inbody-cs-conference-agenda'
          slot-name: 'Production'
          package: .
